name: Stats
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
        
          user: samuelscheit
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          config_twemoji: yes
          repositories: 500
          plugin_achievements: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: starlark, shell, batchfile, vue
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 20
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_traffic: yes
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
